### ISSUE TITLE
JS initialized widgets initial state overridden by backend

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#30]
Assuming a Point widget and PointModel are defined,

```js
                    var that = this;
                    this.model.widget_manager.create_model({
                        model_name: 'PointModel', 
                        widget_class: 'paper.Point'})
                        .then(function(model) {
                            model.set('x', point.x);
                            model.set('y', point.y);
                            model.save_changes(that.callbacks());
// ...
```

I also tried

```js
                    var that = this;
                    this.model.widget_manager.create_model({
                        model_name: 'PointModel', 
                        widget_class: 'paper.Point'})
                        .then(function(model) {
                            model.state_change = model.state_change.then(function() {
                                model.set('x', point.x);
                                model.set('y', point.y);
                                model.save_changes(that.callbacks());
// ...
```

despite point.x and point.y being non-zero, the 0 values of the backend class always override the values set by the frontend during construction.  See a log of the sent&recieved msgs, from the front end's perspective:

```
send Object {x: 146, y: 62}
paper_widget.js:132 3
widget.js:171 recv Object {version: 0, msg_throttle: 3, y: 0, x: 0, _view_name: null…}
```

**Comment by jdfreder** [comment]
The following is a work around:

```js
                    var that = this;
                    this.model.widget_manager.create_model({
                        model_name: 'PointModel', 
                        widget_class: 'paper.Point'})
                        .then(function(model) {
                            model.request_state(that.callbacks()).then(function() {
                                model.set('x', point.x);
                                model.set('y', point.y);
                                model.save_changes(that.callbacks());
```

I still think there should be a slick way to do this.  `request_state` feels awkward in this context.

**Comment by SylvainCorlay** [comment]
I am looking into something very similar at the moment. Do you append your `Point` to a container widget afterwards?

**Comment by jdfreder** [comment]
Yes

**Comment by jdfreder** [comment]
Maybe the solution here is to include the initial state push as meta data of the comm open call.  That would allow the behavior to be symmetric.

**Comment by SylvainCorlay** [comment]
This is also related to #71 IMO.

**Comment by SylvainCorlay** [comment]
Do you consider this solved with the state being pushed at comm-open?

**Comment by jdfreder** [comment]
I *think* it's still broken.  The right thing to do, but inconvenient for us, is redefine the Python model in Javascript.  As opposed to our current design, where the model in Javascript "copies" the model in Python.

It would be nice to avoid that if possible...

**Comment by bollwyvl** [comment]
Based on the current state of affairs, this pattern is more accurate version of the [above](https://github.com/ipython/ipywidgets/issues/30#issuecomment-101062125):
```js
var that = this;
                    this.model.widget_manager.create_model({
                        model_name: 'PointModel', 
                        widget_class: 'paper.Point'})
                        .then(function(model) {
                            model.set('x', point.x);
                            model.set('y', point.y);
                            model.save_changes(that.callbacks());
```
(without the `request_state` then layer)

**Comment by jdfreder** [comment]
To clarify: I think, even though the code snippets I provide no longer illustrate the problem, you can still run into trouble by state pushed from the backend, which was never set by the frontend.  IOW, those defaults still exist in the backend, and can still surprise the unsuspecting frontend.

**Comment by jdfreder** [comment]
Thanks @bollwyvl !

**Comment by SylvainCorlay** [comment]
This is solved now.
