### ISSUE TITLE
Checkboxes width and max_width not updating

### ISSUE THREAD

**Issue by stsievert** [ipython/ipywidgets#861]
When I create a checkbox and change the width, it doesn't get reflected in the browser.

Buggy behavior:
<img width="523" alt="screen shot 2016-10-30 at 10 20 33 pm" src="https://cloud.githubusercontent.com/assets/1320475/19843327/5304a730-9eef-11e6-90fd-168a6bf7ee89.png">

After editing the max-width property in the CSS with Chrome's debugging to 800ex:
<img width="159" alt="screen shot 2016-10-30 at 10 20 10 pm" src="https://cloud.githubusercontent.com/assets/1320475/19843326/4f9d41d8-9eef-11e6-9d85-86cd6a3956e4.png">

**Comment by jasongrout** [comment]
The problem in ipywidgets master is that the checkbox is wider, but the label subelement is not made any wider, it's still fixed at 160px. @SylvainCorlay - thoughts?

**Comment by SylvainCorlay** [comment]
Closing as fixed with the new Labeled Widget base:

<img width="713" alt="screen shot 2017-02-03 at 3 45 06 pm" src="https://cloud.githubusercontent.com/assets/2397974/22595440/c631edac-ea27-11e6-8249-ce2bbee55d77.png">

**Comment by jasongrout** [comment]
It's not fixed yet:
```python
import ipywidgets as w
b=w.Checkbox(description='a really, really, *really*, long name ')
b.layout.width='800ex'
b.layout.max_width='800ex'
b
```
<img width="696" alt="screen shot 2017-02-03 at 2 49 40 pm" src="https://cloud.githubusercontent.com/assets/192614/22605981/1b03fe4a-ea20-11e6-9765-255498091cdb.png">

**Comment by jasongrout** [comment]
The problem here is that we have a max width on the label, which is fine usually. The checkbox is the thing that expands here. However, a workaround is to use the actual Label widget:

```python
import ipywidgets as w
b=w.Checkbox()
c=w.Label("a really really really really really long name")
c.layout.width='auto'
w.HBox([c,b])
```
This doesn't let you do the accessible thing of saying the label is for another input, so that's bad. But it does let you see the full label.

Do you think that instead, we should take off the max width for a label that is part of a widget?

**Comment by SylvainCorlay** [comment]
I think that we can close the issue here.

**Comment by jasongrout** [comment]
Sure, we have a workaround above. If this still is a big issue, we can change the css for the checkbox to ignore the label max width.
